### PR TITLE
Tasking VX support v2

### PR DESCRIPTION
**Pull request by mdanilov**
Tasking VX support v2

- rebase on the latest mozilla/sccache
- add handling for more flags and args
- handle --dep-flag without parameter
- add tests

### CODE REVIEW

**Comment by flxo** [comment]
Think this PR should go to the `tasking` branch instead of master?

**Comment by mdanilov** [comment]
> Think this PR should go to the `tasking` branch instead of master?

Done. But still, there will be other commits since I did the rebase on the mozilla/sccache/master, is that correct?

**Comment by flxo** [comment]
> > Think this PR should go to the `tasking` branch instead of master?
> 
> Done. But still, there will be other commits since I did the rebase on the mozilla/sccache/master, is that correct?

Sure. The `tasking` hasn't been updated for some time.

**Comment by mdanilov** [comment]
Ah, sorry don't understand this GitHub pull request UI, something goes wrong, I need to create another one :)

**Pull request closed without merging**
